### ISSUE TITLE
The ServiceControl.Retry.AcknowledgementQueue header is not translated correctly

### ISSUE THREAD

**Issue by Floopy-Doo** [Particular/NServiceBus.Transport.Bridge#218]
We are run into an issue when using ServiceControl on AzureServiceBus <-> Bridge <-> Endpoint on MSMQ (with remote queues).

Our system is deployed in the following fashion (simplified):
Host A: ServiceControl | No MSMQ Queue
Host B: Bridge / EndpointA | MSMQQueueEndpointA / MSMQQueueError / MSMQQueueAudit
Host C: EndpointB | MSMQQueueEndpointB

We are transitioning form MSMQ to ASB and our bridge currently only forwards Error- / Audit-Queue to ServiceBus.

Our problem:
Whenever we retry a message for EndpointB and the endpoint succeeds with the retry and acknowledgement message should be sent to the audit queue, as well as a retry acknowledgment system message is sent. Here is where the error occurs: the header _ServiceControl.Retry.AcknowledgementQueue_ got no address translation when being moved by the bridge and therefor EndpointB tries to send the acknowledgment message to a local queue instead of a remote one. (instance mapping does not help as well)

NSB Versions of Endpoints/Bridge: 7.8.x and 8.0.3
Bridge Version: 1.0.1
ServiceControl Version: 4.27.6

We tried instance mapping on EndpointB -> does not help
We figured out that the bridge does not allow incoming / outgoing message mutators

Any suggestion on how to solve this issue?

**Comment by andreasohlund** [comment]
This definitely looks like a bug, we've started to look into it!

**Comment by andreasohlund** [comment]
@Floopy-Doo I've raised https://github.com/Particular/NServiceBus.Transport.Bridge/pull/222 that should address this.

Would you be able to[ try out the temp nuget package](https://github.com/Particular/NServiceBus.Transport.Bridge/actions/runs/4314208596) just to verify that we haven't missed anything?

**Comment by Floopy-Doo** [comment]
@andreasohlund I'll try out the temp packages and get back to you

**Comment by Floopy-Doo** [comment]
@andreasohlund I can verify that the bug fix works as intendent within our system.
Thank you very much for quick response and fix.

**Comment by Floopy-Doo** [comment]
@andreasohlund 
Thank you for the prompt fix. The address translation does work when retrying message from service control. EndpointB does successfully retry the message and correctly send to the correct AcknowledgementQueue. The acknowledgement message gets then put into the bridge.error queue due to the header translation trying to translate MSMQErrorQueue@HostB and there is no mapping for it.
If I were to add this mapping, then the MSMQErrorQueue would be defined on both transports and this causes the bridge to not start.

**Comment by andreasohlund** [comment]
Thanks for testing @Floopy-Doo , I'll look into this further

**Comment by andreasohlund** [comment]
>The acknowledgement message gets then put into the bridge.error queue due to the header translation trying to translate MSMQErrorQueue@HostB and there is no mapping for it.

Trying to reproduce this now, in the meantime can you share the headers on that message that ends up in the bridge error queue? (You can use  https://www.cogin.com/mq/ and look at the `Extension` property to see all the headers)

**Comment by Floopy-Doo** [comment]
I had to alter some of the data within the header values due to privacy reasons.

See file from attachment.
[headers.txt](https://github.com/Particular/NServiceBus.Transport.Bridge/files/10898359/headers.txt)

**Comment by andreasohlund** [comment]
Thanks!

Looking at the error

```
System.Exception: Failed to shovel message for endpoint MSMQQueueAudit with id bd3c8193-fb38-4dfc-aa55-ab79572f1215\74856 from msmq to azureservicebus ---&gt; System.Exception: No target address mapping could be found for source address: MSMQQueueError@HostB
   at EndpointRegistry.TranslateToTargetAddress(String sourceAddress) in /_/src/NServiceBus.Transport.Bridge/EndpointRegistry.cs:line 63
```

it seems like its the successfully retried message that fails to be shoveled through the MSMQAudit queue due to the `ServiceControl.Retry.AcknowledgementQueue` header being translated.

```
    <Key>ServiceControl.Retry.AcknowledgementQueue</Key>
    <Value>MSMQQueueError@HostB</Value>
```

Does that make sense?

I'll try to reproduce this with a test and fix it.

Thank you so much for helping out with debugging this!

**Comment by andreasohlund** [comment]
@Floopy-Doo think(🤞 ) I got it sorted now, would you be able to test https://github.com/Particular/NServiceBus.Transport.Bridge/suites/11396136978/artifacts/586715216 ?

**Comment by Floopy-Doo** [comment]
@andreasohlund Yes that's what I assume is happening. I think the replay is treated as retry message even though I would assume it to be an audit message.

I will check out the new package and give you feed back on it. Thank you very much for you time and help on this.

**Comment by Floopy-Doo** [comment]
I was able to verify that the fix does both operation correctly
* Translate header for retry acknowledgment queue
* Transport response to acknowledgment queue via bridge

Thank you again.
Cheers

**Comment by andreasohlund** [comment]
@Floopy-Doo https://www.nuget.org/packages/NServiceBus.Transport.Bridge/1.0.2 is available now
